name: foundationdb
version: 6.0.18
summary: A multi-model NoSQL database. 
description:| 
An open source, distributed, transactional key-value store.

adopt-info: foundationdb

confinement: devmode
base: core18

architectures:
  - build-on: amd64
  
apps:
  foundationdb:
    command: foundationdb 

parts:
  foundationdb:
    plugin: dump
    source-type: tar
    source:
      - on amd64: https://www.foundationdb.org/downloads/$SNAPCRAFT_PROJECT_VERSION/linux/fdb_$SNAPCRAFT_PROJECT_VERSION.tar.gz
      

